# Define o menu principal que será aberto ao executar /skills
main-menu: main
# Caso a skull-meta estiver inválida ou nula, usará essa por padrão.
invalid-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDE2YzVkOTAwNzA4OGYxN2E0ZGI1MmRmZTI4NmI5ZTFhMTdmYTE0NTQwODc5YTRmNWYzZmEyMTFhMzJhMDdiIn19fQ=="
# Configuraçao da BossBar
bossbar:
  enabled: true
  color: GREEN
  style: SEGMENTED_10
  duration: 60 # em ticks (20 ticks = 1 segundo)
  title: "§eXP em %path_display%: §b%xp%§7/§b%nextxp%"
